export const ON_EMPLOYEE_SELECTED = "ON_EMPLOYEE_SELECTED";
export const ON_EMPLOYEE_DELETED = "ON_EMPLOYEE_DELETED";
export const ON_REQUEST_SEND = "ON_REQUEST_SEND";
export const ON_REQUEST_COMPLETE = "ON_REQUEST_COMPLETE";
export const ON_EMPLOYEE_RECEIVED = "ON_EMPLOYEE_RECEIVED";

